services:
  php:
    image: php:8.1-fpm
    build: .
    container_name: symfony_php
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - symfony_network

  web:
    image: nginx:alpine
    container_name: symfony_web
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    depends_on:
      - php
    networks:
      - symfony_network

  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - symfony_network

volumes:
  mysql_data:

networks:
  symfony_network:
    driver: bridge
